"""add_reminder_system_v2

Revision ID: 1b8172fc1f41
Revises: 4dc093cdf101
Create Date: 2026-08-17 11:46:20.889268

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b8172fc1f41'
down_revision: Union[str, Sequence[str], None] = '4dc093cdf101'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('auto_create_invoice', sa.Boolean(), nullable=False),
    sa.Column('auto_send_invoice', sa.Boolean(), nullable=False),
    sa.Column('acompte_percent', sa.Float(), nullable=True),
    sa.Column('invoice_prefix', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('invoice_number_format', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('default_late_fee_percent', sa.Float(), nullable=False),
    sa.Column('legal_mentions', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_settings_user_id'), 'billing_settings', ['user_id'], unique=True)
    op.create_table('payment_schedule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('percent', sa.Float(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('trigger_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'INVOICED', 'PAID', 'CANCELLED', name='milestonestatus'), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=True),
    sa.Column('invoiced_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_schedule_document_id'), 'payment_schedule', ['document_id'], unique=False)
    op.create_index(op.f('ix_payment_schedule_invoice_id'), 'payment_schedule', ['invoice_id'], unique=False)
    op.alter_column('document', 'origin',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document', 'origin',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_payment_schedule_invoice_id'), table_name='payment_schedule')
    op.drop_index(op.f('ix_payment_schedule_document_id'), table_name='payment_schedule')
    op.drop_table('payment_schedule')
    op.drop_index(op.f('ix_billing_settings_user_id'), table_name='billing_settings')
    op.drop_table('billing_settings')
    # ### end Alembic commands ###
