"""add client token

Revision ID: 3709db93c332
Revises: f543424d8af7
Create Date: 2026-07-08 12:40:39.871640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '3709db93c332'
down_revision: Union[str, Sequence[str], None] = 'f543424d8af7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('client_token', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.add_column('document', sa.Column('client_token_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_document_client_token'), 'document', ['client_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_client_token'), table_name='document')
    op.drop_column('document', 'client_token_email')
    op.drop_column('document', 'client_token')
    # ### end Alembic commands ###
