"""initial migration

Revision ID: 7c4f8a025c1a
Revises: 
Create Date: 2026-04-21 23:32:31.616999

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c4f8a025c1a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tax_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payment_info', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('client',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documenttemplate',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('primary_color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('secondary_color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('accent_color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text_color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('background_color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('font_family', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('header_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('footer_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('show_bank_details', sa.Boolean(), nullable=False),
    sa.Column('show_tax_id', sa.Boolean(), nullable=False),
    sa.Column('layout_style', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reminderconfig',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('reminder_1_enabled', sa.Boolean(), nullable=False),
    sa.Column('reminder_1_days', sa.Integer(), nullable=False),
    sa.Column('reminder_1_subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reminder_2_enabled', sa.Boolean(), nullable=False),
    sa.Column('reminder_2_days', sa.Integer(), nullable=False),
    sa.Column('reminder_2_subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reminder_3_enabled', sa.Boolean(), nullable=False),
    sa.Column('reminder_3_days', sa.Integer(), nullable=False),
    sa.Column('reminder_3_subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('stop_on_view', sa.Boolean(), nullable=False),
    sa.Column('stop_on_payment', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminderconfig_user_id'), 'reminderconfig', ['user_id'], unique=False)
    op.create_table('document',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('DEVIS', 'FACTURE', name='documenttype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'PAID', 'VIEWED', name='documentstatus'), nullable=False),
    sa.Column('number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['documenttemplate.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_number'), 'document', ['number'], unique=False)
    op.create_table('documentitem',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_cents', sa.Integer(), nullable=False),
    sa.Column('tax_rate', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documentview',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentview_document_id'), 'documentview', ['document_id'], unique=False)
    op.create_table('reminderlog',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('reminder_level', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='reminderstatus'), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminderlog_document_id'), 'reminderlog', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reminderlog_document_id'), table_name='reminderlog')
    op.drop_table('reminderlog')
    op.drop_index(op.f('ix_documentview_document_id'), table_name='documentview')
    op.drop_table('documentview')
    op.drop_table('documentitem')
    op.drop_index(op.f('ix_document_number'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_reminderconfig_user_id'), table_name='reminderconfig')
    op.drop_table('reminderconfig')
    op.drop_table('documenttemplate')
    op.drop_table('client')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')

    op.execute("DROP TYPE IF EXISTS reminderstatus")
    op.execute("DROP TYPE IF EXISTS documentstatus")
    op.execute("DROP TYPE IF EXISTS documenttype")
    # ### end Alembic commands ###
