"""add_paid_at_to_document

Revision ID: 8f7ced82a0ff
Revises: ceb0103c0baf
Create Date: 2026-08-13 12:22:29.424683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f7ced82a0ff'
down_revision: Union[str, Sequence[str], None] = 'ceb0103c0baf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('paid_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'paid_at')
    # ### end Alembic commands ###
