"""add_reminder_system

Revision ID: aecea1cafe60
Revises: 8f7ced82a0ff
Create Date: 2026-08-17 10:36:05.987067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aecea1cafe60'
down_revision: Union[str, Sequence[str], None] = '8f7ced82a0ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('auto_create_invoice', sa.Boolean(), nullable=False),
    sa.Column('auto_send_invoice', sa.Boolean(), nullable=False),
    sa.Column('acompte_percent', sa.Float(), nullable=True),
    sa.Column('invoice_prefix', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('invoice_number_format', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('default_late_fee_percent', sa.Float(), nullable=False),
    sa.Column('legal_mentions', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_settings_user_id'), 'billing_settings', ['user_id'], unique=True)
    op.create_table('payment_schedule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('percent', sa.Float(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('trigger_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'INVOICED', 'PAID', 'CANCELLED', name='milestonestatus'), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=True),
    sa.Column('invoiced_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_schedule_document_id'), 'payment_schedule', ['document_id'], unique=False)
    op.create_index(op.f('ix_payment_schedule_invoice_id'), 'payment_schedule', ['invoice_id'], unique=False)
    op.add_column('document', sa.Column('invoice_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('document', sa.Column('source_document_id', sa.Uuid(), nullable=True))
    op.add_column('document', sa.Column('origin', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('document', sa.Column('paid_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_document_source_document_id'), 'document', ['source_document_id'], unique=False)
    op.create_foreign_key(None, 'document', 'document', ['source_document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.drop_index(op.f('ix_document_source_document_id'), table_name='document')
    op.drop_column('document', 'paid_at')
    op.drop_column('document', 'origin')
    op.drop_column('document', 'source_document_id')
    op.drop_column('document', 'invoice_type')
    op.drop_index(op.f('ix_payment_schedule_invoice_id'), table_name='payment_schedule')
    op.drop_index(op.f('ix_payment_schedule_document_id'), table_name='payment_schedule')
    op.drop_table('payment_schedule')
    op.drop_index(op.f('ix_billing_settings_user_id'), table_name='billing_settings')
    op.drop_table('billing_settings')
    # ### end Alembic commands ###
