"""add layout_style to document

Revision ID: b05e400d0318
Revises: e0ddd26de4fa
Create Date: 2026-06-24 11:57:11.791548

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b05e400d0318'
down_revision: Union[str, Sequence[str], None] = 'e0ddd26de4fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('layout_style', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'layout_style')
    # ### end Alembic commands ###
