"""add_payment_schedule_table

Revision ID: ceb0103c0baf
Revises: 6e675a41d886
Create Date: 2026-08-10 13:20:40.155241

"""
from typing import Sequence, Union
import  sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceb0103c0baf'
down_revision: Union[str, Sequence[str], None] = '6e675a41d886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_schedule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('percent', sa.Float(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('trigger_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'INVOICED', 'PAID', 'CANCELLED', name='milestonestatus'), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=True),
    sa.Column('invoiced_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_schedule_document_id'), 'payment_schedule', ['document_id'], unique=False)
    op.create_index(op.f('ix_payment_schedule_invoice_id'), 'payment_schedule', ['invoice_id'], unique=False)
    op.drop_constraint('uq_billing_settings_user_id', 'billing_settings', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_billing_settings_user_id', 'billing_settings', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_payment_schedule_invoice_id'), table_name='payment_schedule')
    op.drop_index(op.f('ix_payment_schedule_document_id'), table_name='payment_schedule')
    op.drop_table('payment_schedule')
    # ### end Alembic commands ###
