"""add_notes_to_document

Revision ID: e0ddd26de4fa
Revises: 7c4f8a025c1a
Create Date: 2026-06-10 14:01:40.197437

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0ddd26de4fa'
down_revision: Union[str, Sequence[str], None] = '7c4f8a025c1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'notes')
    # ### end Alembic commands ###
