"""document validation

Revision ID: f543424d8af7
Revises: 9c57d82ac368
Create Date: 2026-07-08 12:19:15.350114

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f543424d8af7'
down_revision: Union[str, Sequence[str], None] = '9c57d82ac368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('accepted_at', sa.DateTime(), nullable=True))
    op.add_column('document', sa.Column('refused_at', sa.DateTime(), nullable=True))
    op.add_column('document', sa.Column('refusal_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('document', sa.Column('signature_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.drop_index('ix_document_project_id', table_name='document')
    op.drop_constraint('document_project_id_fkey', 'document', type_='foreignkey')
    op.create_foreign_key(None, 'document', 'project', ['project_id'], ['id'])
    op.alter_column('project', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_index('ix_project_client_id', table_name='project')
    op.drop_index('ix_project_status', table_name='project')
    op.drop_index('ix_project_user_id', table_name='project')
    op.drop_index('ix_project_attachment_project_id', table_name='project_attachment')
    op.drop_constraint('project_attachment_project_id_fkey', 'project_attachment', type_='foreignkey')
    op.create_foreign_key(None, 'project_attachment', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_attachment', type_='foreignkey')
    op.create_foreign_key('project_attachment_project_id_fkey', 'project_attachment', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_project_attachment_project_id', 'project_attachment', ['project_id'], unique=False)
    op.create_index('ix_project_user_id', 'project', ['user_id'], unique=False)
    op.create_index('ix_project_status', 'project', ['status'], unique=False)
    op.create_index('ix_project_client_id', 'project', ['client_id'], unique=False)
    op.alter_column('project', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.create_foreign_key('document_project_id_fkey', 'document', 'project', ['project_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_document_project_id', 'document', ['project_id'], unique=False)
    op.drop_column('document', 'signature_name')
    op.drop_column('document', 'refusal_reason')
    op.drop_column('document', 'refused_at')
    op.drop_column('document', 'accepted_at')
    # ### end Alembic commands ###
